#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# Local dev keys belong in .env.local, which is gitignored.
ENV_FILE=".env.local"

# Cloudflare's published test keys. Not secrets — they are in the docs, and in
# docs/operations/contact-pipeline.md.
TEST_SITE_KEY="1x00000000000000000000AA"
TEST_SECRET_KEY="1x0000000000000000000000000000000AA"

# vercel_env NAME VALUE ENVIRONMENT — upsert one variable in one Vercel
# environment. Removes first, because `vercel env add` will not overwrite.
# vercel_env NAME VALUE ENVIRONMENT — upsert one variable in one Vercel
# environment. Removes first, because `vercel env add` will not overwrite.
# Vercel's own output is shown on failure: a variable that silently does not
# land produces a build error many minutes later that names the variable but
# not the reason, which is a bad trade for two lines of output here.
vercel_env() {
  local name="$1" value="$2" target="$3" out
  npx vercel env rm "$name" "$target" --yes >/dev/null 2>&1 || true
  if out=$(printf '%s' "$value" | npx vercel env add "$name" "$target" 2>&1); then
    printf '  %s✓ set%s %s in Vercel %s\n' "$GREEN" "$RESET" "$name" "$target"
  else
    SKIPPED+=("Vercel $target: $name")
    warn "could not set $name in Vercel $target — Vercel said:"
    printf '%s\n' "$out" | sed 's/^/        /'
  fi
}

# verify_vercel_env — read back what is actually there. The wizard reporting
# success is not the same as the platform having stored it.
verify_vercel_env() {
  local target name missing=0 listing
  for target in production preview development; do
    listing=$(npx vercel env ls "$target" 2>/dev/null || true)
    for name in NEXT_PUBLIC_TURNSTILE_SITE_KEY TURNSTILE_SECRET_KEY; do
      if grep -q "$name" <<<"$listing"; then
        printf '  %s✓%s %-32s %s\n' "$GREEN" "$RESET" "$name" "$target"
      else
        printf '  %s✗%s %-32s %s %s(missing)%s\n' "$RED" "$RESET" "$name" "$target" "$RED" "$RESET"
        missing=1
      fi
    done
  done
  return $missing
}

banner "Cloudflare Turnstile setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare — create the Turnstile site"
say "This produces the real key pair, used by production only."
open_url "https://dash.cloudflare.com/?to=/:account/turnstile"
step "Click 'Add site'. Name it anything — 'personal-portfolio' is fine."
step "Widget mode: Managed. It is invisible for most visitors and only shows"
say  "  an interaction when Cloudflare is unsure."
step "Hostnames — add ALL of these:"
say  "    mikepeerawit.com"
say  "    www.mikepeerawit.com"
say  "    personal-portfolio.vercel.app"
say  "    localhost"
printf '\n'
warn "A hostname that is not listed fails EVERY Challenge, and looks exactly"
note "like a broken contact form. Preview URLs are deliberately absent — see"
note "stage 3."
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare — copy the key pair"
say "Both keys are on the site's settings page once it is created."
step "Copy the Site Key (public — it ships to the browser)."
ask REAL_SITE_KEY "Paste the site key:"
step "Copy the Secret Key (never leaves the server)."
ask_secret REAL_SECRET_KEY "Paste the secret key:"

if [[ -z "$REAL_SITE_KEY" || -z "$REAL_SECRET_KEY" ]]; then
  printf '\n'; warn "Both keys are required — production cannot build without them."
  confirm "Continue anyway and set production by hand later?" || exit 1
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Vercel — Production gets the real pair, Preview gets test keys"
say "Production is the only environment whose hostname is on the list above."
printf '\n'
step "Preview deployments get a generated hostname per branch"
say  "  (personal-portfolio-git-<branch>.vercel.app), which can never be on"
say  "  the Turnstile hostname list. Real keys there would refuse EVERYONE on"
say  "  every preview — indistinguishable from a broken form."
step "So Preview and Development get Cloudflare's always-passing test pair."
say  "  The cost: a preview proves the form, the wire and the mail path work,"
say  "  and proves nothing about Cloudflare. That is the right trade."
printf '\n'
if confirm "Write these to Vercel now?"; then
  if [[ -n "$REAL_SITE_KEY" && -n "$REAL_SECRET_KEY" ]]; then
    vercel_env NEXT_PUBLIC_TURNSTILE_SITE_KEY "$REAL_SITE_KEY"   production
    vercel_env TURNSTILE_SECRET_KEY           "$REAL_SECRET_KEY" production
  else
    SKIPPED+=("Vercel production: both Turnstile keys")
  fi

  for target in preview development; do
    vercel_env NEXT_PUBLIC_TURNSTILE_SITE_KEY "$TEST_SITE_KEY"   "$target"
    vercel_env TURNSTILE_SECRET_KEY           "$TEST_SECRET_KEY" "$target"
  done

  printf '\n'
  say "Reading back what Vercel actually stored:"
  printf '\n'
  if verify_vercel_env; then
    printf '\n'
    note "All six present. The build will get past next.config.ts."
  else
    printf '\n'
    warn "Something did not land. Re-run this stage, or add the missing ones"
    note "in the dashboard. A PR builds in PREVIEW — a gap there fails the"
    note "deployment even when production is complete."
    confirm "Continue anyway?" || exit 1
  fi
else
  warn "skipped — nothing written to Vercel"
  SKIPPED+=("all six Vercel variables")
fi
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Local — the same test pair in .env.local"
say "No real key belongs in .env.local. The test pair behaves identically"
say "for everything except actually proving a human is present."
write_env NEXT_PUBLIC_TURNSTILE_SITE_KEY "$TEST_SITE_KEY"
write_env TURNSTILE_SECRET_KEY "$TEST_SECRET_KEY"
printf '\n'
note "To see what a refused visitor sees, swap in the always-BLOCKING pair:"
note "  site 2x00000000000000000000AB / secret 2x0000000000000000000000000000000AA"
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Vercel — redeploy the build that failed"
say "PR #40's deployment failed on the missing site key. With the variables"
say "set, it needs a fresh build; Vercel does not retry automatically."
open_url "https://vercel.com/mikepeerawits-projects/personal-portfolio/deployments"
step "Find the most recent failed deployment for"
say  "  feat/challenge-bots-at-the-form"
step "Use the ⋯ menu → Redeploy."
printf '\n'
say "Then confirm it goes green:"
say "  gh pr checks 40"
printf '\n'
warn "If it fails again on a missing variable, one of the six did not land —"
note "check with: npx vercel env ls"
pause

finish
